
name: My Awesome CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          # Path to Doxyfile
          doxyfile-path: Euler-Project/Doxyfile # default is ./Doxyfile
          # Working directory
          working-directory: . # default is .
      - name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
        uses: ArtificialAmateur/cpp-linter-action@0.01
